"""rename address

Revision ID: 454d89d05da6
Revises: 07b612360d57
Create Date: 2024-10-03 15:05:06.023792

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '454d89d05da6'
down_revision = '07b612360d57'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('departments', 'address',  new_column_name='location')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('departments', 'location',  new_column_name='address')
    # ### end Alembic commands ###
